version: "3"
services:
  prototype-kit:
    build:
      context: .
    image: prototype-kit
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run dev
    