name: Dev deployment

on:
  push:
    branches:
      - feat/pipeline2
  workflow_dispatch:

env:
  ENVIRONMENT: infrastructure
  TIMEZONE: 'Europe/London'
  APP_NAME: 'app-prototypekit-dev-003'
  PACKAGE_PATH: '.'

jobs:
  # 1. Setup deployment variables
  setup:
    name: Setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.ENVIRONMENT }}
      timezone: ${{ env.TIMEZONE }}
    steps:
    - name: Environment 🧪
      run: echo "Environment set to ${{ env.ENVIRONMENT }}"

    - name: Timezone 🌐
      run: echo "Timezone set to ${{ env.TIMEZONE }}"

  build:
    name: Build and deploy
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: npm install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.APP_NAME }}
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.APP_NAME }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .