name: Build and deploy

on:
  push:
    branches:
      - feat/pipeline2
  workflow_dispatch:

env:
  ENVIRONMENT: infrastructure
  TIMEZONE: 'Europe/London'
  APP_NAME: 'app-prototypekit-dev-002'
  PACKAGE_PATH: '.'

jobs:
  # 1. Setup deployment variables
  setup:
    name: Setup 🔧
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.ENVIRONMENT }}
      timezone: ${{ env.TIMEZONE }}
    steps:
    - name: Environment 🧪
      run: echo "Environment set to ${{ env.ENVIRONMENT }}"

    - name: Timezone 🌐
      run: echo "Timezone set to ${{ env.TIMEZONE }}"

  build:
    name: PrototypeKit
    needs: setup
    environment: ${{ needs.setup.outputs.environment }}
    env:
      ENVIRONMENT: ${{ needs.setup.outputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Repository 🗃️
        uses: actions/checkout@v3
      
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'