name: Dev deployment

on:
  push:
    branches:
      - feat/pipeline2
  workflow_dispatch:

env:
  env: infrastructure
  ARTIFACT_NAME: app-prototypekit-dev-003
  ARTIFACT_FILE_NAME: prototype-kit
  AZURE_WEBAPP_NAME: app-prototypekit-dev-003
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "14.x"

permissions:
  contents: read
  id-token: write

############ ENVIRONMENT ############

jobs:
  environment:
    name: Environment setup
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ env.environment }}
    steps:
      - name: Initialise Environment
        run: echo "Setting up ${{ env.environment }} environment"

  ############ BUILD ############

  build:
    name: Build artifact
    runs-on: ubuntu-latest
    needs: environment
    environment:
      name: ${{ needs.environment.outputs.environment }}

    steps:
      # Checkout latest commit
      - name: 1. Latest commit
        uses: actions/checkout@v3

      # Setup Node.js
      - name: 2. Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      # NPM Scripts - install, build and test
      - name: 3. NPM Scripts
        run: |
          npm install

      # ZIP artifact
      - name: 4. Archive artifact
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ env.ARTIFACT_FILE_NAME }}

      # Upload artifact
      - name: 5. Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

  ############ DEPLOY ############

  deploy:
    name: Deploy artifact
    runs-on: ubuntu-latest
    needs: [environment, build]
    environment:
      name: ${{ needs.environment.outputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      # Deploy artifact
      - name: Deploy artifact
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.environment }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_24C8722156D14DDBA923A756E4EC5FF9 }}
          package: "."